### ISSUE TITLE
why don't you use pen and paper? lol, useless repo

### ISSUE THREAD

**Issue by zoematr** [Di0nigi/ProbabilityTester#1]
why did you code a probability tester? is it because you are not capable of computing probabilities with pen and paper? lame

**Comment by SchulzKilian** [comment]
This seems like a very valid issue. I hope the repository owner does something to address this.

**Comment by Di0nigi** [comment]
Sure I understand your point of view, I think tho that this is a smarter way to go about these kind of problems, I wouldn't expect you to understand especially after having a quick look at your github :)
